{{- if .Values.exporter.enabled -}}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "cassandra.name" . }}-metric
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cassandra.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    cassandra.datastax.com/cluster: {{ .Values.clusterName }}
    cassandra.datastax.com/datacenter: {{ .Values.datacenterName }}
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: {{ .Values.exporter.port }}
      targetPort: {{ .Values.exporter.port }}
  selector:
    cassandra.datastax.com/cluster: {{ .Values.clusterName }}
    cassandra.datastax.com/datacenter: {{ .Values.datacenterName }}
  clusterIP: None
  type: ClusterIP
{{- end -}}
